import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Camera, Upload, Loader2, RotateCcw, Share2, Download, Clock, ChevronRight, Leaf, AlertTriangle, Shield, FlaskConical, Stethoscope } from "lucide-react";
import Layout from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { tr } from "@/lib/translations";
import { SAMPLE_IMAGES, generateSampleCanvas, type SampleImage } from "@/lib/diseaseDatabase";
import { analyzeImageColors, matchDisease, matchSampleDisease, type AnalysisResult } from "@/lib/imageAnalyzer";
import { getScanHistory, saveScanToHistory } from "@/lib/api";

type ScanStep = "upload" | "analyzing" | "results" | "history";

export default function Scanner() {
  const { language } = useLanguage();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [step, setStep] = useState<ScanStep>("upload");
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [selectedSampleId, setSelectedSampleId] = useState<string | null>(null);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [activeTab, setActiveTab] = useState<"organic" | "chemical" | "prevention">("organic");
  const [sampleImages, setSampleImages] = useState<{ sample: SampleImage; dataUrl: string }[]>([]);

  // Generate sample images on mount
  useEffect(() => {
    const imgs = SAMPLE_IMAGES.map(s => ({ sample: s, dataUrl: generateSampleCanvas(s) }));
    setSampleImages(imgs);
  }, []);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setSelectedSampleId(null);
    const reader = new FileReader();
    reader.onload = (ev) => setSelectedImage(ev.target?.result as string);
    reader.readAsDataURL(file);
  };

  const handleSelectSample = (sample: SampleImage, dataUrl: string) => {
    setSelectedImage(dataUrl);
    setSelectedSampleId(sample.expectedDisease);
  };

  const handleAnalyze = async () => {
    if (!selectedImage) return;
    setStep("analyzing");
    setProgress(0);

    const interval = setInterval(() => {
      setProgress(p => { if (p >= 95) { clearInterval(interval); return 95; } return p + Math.random() * 12; });
    }, 250);

    // Analyze: use sample match or real color analysis
    let analysisResult: AnalysisResult;
    if (selectedSampleId) {
      await new Promise(r => setTimeout(r, 2000));
      analysisResult = matchSampleDisease(selectedSampleId);
    } else {
      const colors = await analyzeImageColors(selectedImage);
      await new Promise(r => setTimeout(r, 1500));
      analysisResult = matchDisease(colors);
    }

    clearInterval(interval);
    setProgress(100);
    setTimeout(() => {
      setResult(analysisResult);
      saveScanToHistory(
        { disease: analysisResult.disease.disease, confidence: analysisResult.confidence, remedy: analysisResult.disease.organicTreatment.steps.join(". ") },
        selectedImage || undefined
      );
      setStep("results");
    }, 500);
  };

  const handleReset = () => {
    setStep("upload"); setSelectedImage(null); setSelectedSampleId(null); setResult(null); setProgress(0);
  };

  const handleShare = () => {
    if (!result) return;
    const text = `🌿 CropDetectionUsingAI Report\n\n🔬 Disease: ${result.disease.disease}\n📊 Confidence: ${Math.round(result.confidence)}%\n⚠️ Severity: ${result.disease.severity}\n\n🌿 Treatment: ${result.disease.organicTreatment.steps[0]}\n\nDownload: ${window.location.href}`;
    if (navigator.share) {
      navigator.share({ title: "Crop Disease Report", text });
    } else {
      window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
    }
  };

  const handleDownloadPDF = () => {
    if (!result) return;
    const content = `
CROP DISEASE DETECTION REPORT
==============================
Date: ${new Date().toLocaleDateString()}

Disease: ${result.disease.disease}
Scientific Name: ${result.disease.scientificName}
Crop: ${result.disease.crop}
Confidence: ${Math.round(result.confidence)}%
Severity: ${result.disease.severity}

SYMPTOMS:
${result.disease.symptoms.map(s => `• ${s}`).join("\n")}

ORGANIC TREATMENT:
${result.disease.organicTreatment.steps.map(s => `• ${s}`).join("\n")}
Frequency: ${result.disease.organicTreatment.frequency}

CHEMICAL TREATMENT:
${result.disease.chemicalTreatment.steps.map(s => `• ${s}`).join("\n")}
Wait Period: ${result.disease.chemicalTreatment.waitPeriod}

PREVENTION:
${result.disease.prevention.map(s => `• ${s}`).join("\n")}

RECOMMENDATIONS:
${result.disease.recommendations.map(s => `• ${s}`).join("\n")}

Generated by CropDetectionUsingAI
    `;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `crop-report-${Date.now()}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  const progressLabel = progress < 25 ? tr("scan.processing", language) : progress < 50 ? tr("scan.runningAI", language) : progress < 80 ? tr("scan.identifying", language) : tr("scan.generating", language);
  const history = getScanHistory();

  const severityColor = (s: string) =>
    s === "Severe" ? "bg-destructive/15 text-destructive border-destructive/30" :
    s === "Moderate" ? "bg-orange-500/15 text-orange-600 border-orange-500/30" :
    "bg-emerald-500/15 text-emerald-600 border-emerald-500/30";

  return (
    <Layout>
      <div className="px-4 pt-4 pb-6 max-w-lg mx-auto">
        {/* Header */}
        <div className="mb-5 flex items-center justify-between">
          <div>
            <h1 className="font-display text-xl font-bold text-foreground flex items-center gap-2">
              <Stethoscope className="h-5 w-5 text-primary" />
              {tr("scan.title", language)}
            </h1>
            <p className="text-xs text-muted-foreground mt-0.5">{tr("scan.subtitle", language)}</p>
          </div>
          <button onClick={() => setStep(step === "history" ? "upload" : "history")}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-muted text-xs font-medium text-foreground">
            <Clock className="h-3.5 w-3.5" /> History ({history.length})
          </button>
        </div>

        <AnimatePresence mode="wait">
          {/* ── UPLOAD STEP ── */}
          {step === "upload" && (
            <motion.div key="upload" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-4">
              {/* Preview / Upload zone */}
              {selectedImage ? (
                <div className="relative rounded-2xl overflow-hidden bg-muted aspect-[4/3] shadow-md">
                  <img src={selectedImage} alt="Crop" className="w-full h-full object-cover" />
                  <button onClick={handleReset} className="absolute top-3 right-3 p-2 rounded-full bg-foreground/60 text-background backdrop-blur-sm">
                    <RotateCcw className="h-4 w-4" />
                  </button>
                </div>
              ) : (
                <button onClick={() => fileInputRef.current?.click()}
                  className="w-full rounded-2xl border-2 border-dashed border-primary/30 bg-primary/5 aspect-[4/3] flex flex-col items-center justify-center hover:bg-primary/10 transition-colors">
                  <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mb-3">
                    <Camera className="h-8 w-8 text-primary" />
                  </div>
                  <p className="text-sm font-medium text-foreground">{tr("scan.takePhoto", language)}</p>
                  <p className="text-xs text-muted-foreground mt-1">JPG, PNG up to 10MB</p>
                </button>
              )}

              {/* Action buttons */}
              <div className="grid grid-cols-2 gap-3">
                <button onClick={() => fileInputRef.current?.click()}
                  className="flex items-center justify-center gap-2 p-3.5 rounded-xl bg-card border border-border shadow-sm text-sm font-medium text-foreground">
                  <Upload className="h-4 w-4 text-primary" /> {tr("scan.upload", language)}
                </button>
                <button onClick={() => fileInputRef.current?.click()}
                  className="flex items-center justify-center gap-2 p-3.5 rounded-xl bg-card border border-border shadow-sm text-sm font-medium text-foreground">
                  <Camera className="h-4 w-4 text-primary" /> {tr("scan.camera", language)}
                </button>
              </div>

              {/* Sample images */}
              <div>
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{tr("scan.sample", language)} Images — Tap to test</h3>
                <div className="grid grid-cols-3 gap-2">
                  {sampleImages.map(({ sample, dataUrl }) => (
                    <button key={sample.id} onClick={() => handleSelectSample(sample, dataUrl)}
                      className={`rounded-xl overflow-hidden border-2 transition-all ${selectedSampleId === sample.expectedDisease ? "border-primary shadow-md" : "border-border"}`}>
                      <img src={dataUrl} alt={sample.label} className="w-full aspect-square object-cover" />
                      <p className="text-[10px] font-medium text-foreground p-1.5 bg-card truncate">{sample.label}</p>
                    </button>
                  ))}
                </div>
              </div>

              <input ref={fileInputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={handleFileSelect} />
              <Button className="w-full h-14 rounded-2xl text-base font-semibold" disabled={!selectedImage} onClick={handleAnalyze}>
                <Leaf className="h-5 w-5 mr-2" /> {tr("scan.analyze", language)}
              </Button>
            </motion.div>
          )}

          {/* ── ANALYZING STEP ── */}
          {step === "analyzing" && (
            <motion.div key="analyzing" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex flex-col items-center justify-center py-16">
              {selectedImage && (
                <div className="w-24 h-24 rounded-2xl overflow-hidden mb-6 shadow-lg border-2 border-primary/30">
                  <img src={selectedImage} alt="" className="w-full h-full object-cover" />
                </div>
              )}
              <Loader2 className="h-10 w-10 text-primary animate-spin mb-4" />
              <div className="w-full max-w-xs bg-muted rounded-full h-2.5 mb-3 overflow-hidden">
                <motion.div className="h-full bg-primary rounded-full" animate={{ width: `${Math.min(progress, 100)}%` }} transition={{ ease: "easeOut" }} />
              </div>
              <p className="text-sm font-medium text-foreground">{progressLabel}</p>
              <p className="text-xs text-muted-foreground mt-1">{Math.round(progress)}%</p>
            </motion.div>
          )}

          {/* ── RESULTS STEP ── */}
          {step === "results" && result && (
            <motion.div key="results" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
              {/* Disease header card */}
              <div className="bg-card rounded-2xl border border-border shadow-sm p-4">
                <div className="flex items-start gap-3">
                  <span className="text-3xl">{result.disease.icon}</span>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-display text-lg font-bold text-foreground leading-tight">{result.disease.disease}</h3>
                    <p className="text-xs text-muted-foreground italic mt-0.5">{result.disease.scientificName}</p>
                    <div className="flex items-center gap-2 mt-2">
                      <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold border ${severityColor(result.disease.severity)}`}>
                        {result.disease.severity} Severity
                      </span>
                      <span className="text-xs text-muted-foreground">Crop: {result.disease.crop}</span>
                    </div>
                  </div>
                </div>

                {/* Confidence meter */}
                <div className="flex items-center gap-3 mt-4 p-3 rounded-xl bg-muted/50">
                  <div className="relative w-14 h-14 flex-shrink-0">
                    <svg className="w-14 h-14 -rotate-90" viewBox="0 0 36 36">
                      <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="hsl(var(--muted))" strokeWidth="3" />
                      <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none"
                        stroke={result.confidence > 85 ? "hsl(var(--primary))" : "hsl(var(--warning, 40 96% 50%))"}
                        strokeWidth="3" strokeDasharray={`${result.confidence}, 100`} />
                    </svg>
                    <span className="absolute inset-0 flex items-center justify-center font-display text-xs font-bold text-foreground">
                      {Math.round(result.confidence)}%
                    </span>
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground">{tr("scan.confidence", language)}</p>
                    <p className="text-[11px] text-muted-foreground">Based on color & pattern analysis</p>
                  </div>
                </div>
              </div>

              {/* Color analysis breakdown */}
              <div className="bg-card rounded-2xl border border-border shadow-sm p-4">
                <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Image Analysis</h4>
                <div className="grid grid-cols-3 gap-2 mb-3">
                  {[
                    { label: "Brown", value: result.colorAnalysis.brown, color: "#8B4513" },
                    { label: "Yellow", value: result.colorAnalysis.yellow, color: "#DAA520" },
                    { label: "White", value: result.colorAnalysis.white, color: "#E0E0E0" },
                    { label: "Green", value: result.colorAnalysis.green, color: "#4CAF50" },
                    { label: "Red", value: result.colorAnalysis.red, color: "#E53935" },
                    { label: "Dark", value: result.colorAnalysis.dark, color: "#333" },
                  ].map(c => (
                    <div key={c.label} className="flex items-center gap-1.5 text-xs">
                      <div className="w-3 h-3 rounded-sm flex-shrink-0" style={{ backgroundColor: c.color }} />
                      <span className="text-muted-foreground">{c.label}</span>
                      <span className="font-bold text-foreground ml-auto">{c.value}%</span>
                    </div>
                  ))}
                </div>
                {result.analysisNotes.length > 0 && (
                  <div className="space-y-1 pt-2 border-t border-border">
                    {result.analysisNotes.map((note, i) => (
                      <p key={i} className="text-[11px] text-muted-foreground flex items-start gap-1.5">
                        <AlertTriangle className="h-3 w-3 text-orange-500 mt-0.5 flex-shrink-0" /> {note}
                      </p>
                    ))}
                  </div>
                )}
              </div>

              {/* Symptoms */}
              <div className="bg-card rounded-2xl border border-border shadow-sm p-4">
                <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2 flex items-center gap-1.5">
                  <AlertTriangle className="h-3.5 w-3.5" /> Symptoms
                </h4>
                <ul className="space-y-1.5">
                  {result.disease.symptoms.map((s, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                      <span className="text-primary mt-0.5">•</span> {s}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Treatment tabs */}
              <div className="bg-card rounded-2xl border border-border shadow-sm overflow-hidden">
                <div className="flex border-b border-border">
                  {([
                    { key: "organic" as const, icon: Leaf, label: tr("scan.organic", language) },
                    { key: "chemical" as const, icon: FlaskConical, label: tr("scan.chemical", language) },
                    { key: "prevention" as const, icon: Shield, label: tr("scan.prevent", language) },
                  ]).map(tab => (
                    <button key={tab.key} onClick={() => setActiveTab(tab.key)}
                      className={`flex-1 py-3 text-xs font-semibold transition-colors flex items-center justify-center gap-1 ${
                        activeTab === tab.key ? "text-primary border-b-2 border-primary bg-primary/5" : "text-muted-foreground"
                      }`}>
                      {tab.label}
                    </button>
                  ))}
                </div>
                <div className="p-4">
                  {activeTab === "organic" && (
                    <div>
                      <ol className="space-y-2">
                        {result.disease.organicTreatment.steps.map((s, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="flex-shrink-0 w-5 h-5 rounded-full bg-primary/10 text-primary text-[10px] font-bold flex items-center justify-center mt-0.5">{i + 1}</span>
                            <p className="text-sm text-foreground">{s}</p>
                          </li>
                        ))}
                      </ol>
                      <p className="text-xs text-muted-foreground mt-3">📅 {result.disease.organicTreatment.frequency}</p>
                    </div>
                  )}
                  {activeTab === "chemical" && (
                    <div>
                      <ol className="space-y-2">
                        {result.disease.chemicalTreatment.steps.map((s, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="flex-shrink-0 w-5 h-5 rounded-full bg-orange-500/10 text-orange-600 text-[10px] font-bold flex items-center justify-center mt-0.5">{i + 1}</span>
                            <p className="text-sm text-foreground">{s}</p>
                          </li>
                        ))}
                      </ol>
                      <p className="text-xs text-muted-foreground mt-3">📅 {result.disease.chemicalTreatment.frequency}</p>
                      <p className="text-xs text-destructive mt-1">⏳ Wait period: {result.disease.chemicalTreatment.waitPeriod}</p>
                    </div>
                  )}
                  {activeTab === "prevention" && (
                    <ul className="space-y-2">
                      {result.disease.prevention.map((s, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-primary mt-0.5">🛡️</span>
                          <p className="text-sm text-foreground">{s}</p>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>

              {/* Recommendations */}
              <div className="bg-primary/5 border border-primary/20 rounded-2xl p-4">
                <h4 className="text-xs font-semibold text-primary uppercase tracking-wide mb-2">📋 Recommendations</h4>
                <ul className="space-y-1.5">
                  {result.disease.recommendations.map((r, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                      <ChevronRight className="h-3.5 w-3.5 text-primary mt-0.5 flex-shrink-0" /> {r}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Actions */}
              <div className="grid grid-cols-3 gap-2">
                <Button variant="outline" className="rounded-xl h-11 text-xs" onClick={handleReset}>
                  <RotateCcw className="h-3.5 w-3.5 mr-1" /> {tr("scan.scanAgain", language)}
                </Button>
                <Button variant="outline" className="rounded-xl h-11 text-xs" onClick={handleShare}>
                  <Share2 className="h-3.5 w-3.5 mr-1" /> Share
                </Button>
                <Button className="rounded-xl h-11 text-xs" onClick={handleDownloadPDF}>
                  <Download className="h-3.5 w-3.5 mr-1" /> Report
                </Button>
              </div>
            </motion.div>
          )}

          {/* ── HISTORY STEP ── */}
          {step === "history" && (
            <motion.div key="history" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-3">
              <h3 className="text-sm font-semibold text-foreground">Scan History</h3>
              {history.length === 0 ? (
                <div className="text-center py-12">
                  <Clock className="h-10 w-10 text-muted-foreground mx-auto mb-3" />
                  <p className="text-sm text-muted-foreground">{tr("dash.noScans", language)}</p>
                </div>
              ) : (
                history.slice(0, 20).map(scan => (
                  <div key={scan.id} className="bg-card rounded-xl border border-border p-3 flex items-center gap-3">
                    {scan.image && <img src={scan.image} alt="" className="w-12 h-12 rounded-lg object-cover flex-shrink-0" />}
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground truncate">{scan.result.disease}</p>
                      <p className="text-xs text-muted-foreground">{new Date(scan.date).toLocaleDateString()} • {Math.round(scan.result.confidence)}% confidence</p>
                    </div>
                  </div>
                ))
              )}
              <Button variant="outline" className="w-full rounded-xl" onClick={() => setStep("upload")}>
                <RotateCcw className="h-4 w-4 mr-2" /> Back to Scanner
              </Button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </Layout>
  );
}
